import { LegalPage } from '@/components/legal/legal-page';
export const metadata = { title: 'Privacidade e LGPD | RIGOR' };
export default function PrivacyPage() {
  return <LegalPage title="Política de Privacidade" description="Como a RIGOR trata dados pessoais em conformidade com a Lei Geral de Proteção de Dados.">
    <section><h2>1. Papéis no tratamento</h2><p>A RIGOR atua como controladora dos dados de cadastro, contratação, segurança e relacionamento comercial. Para dados de trabalhadores, clientes e fornecedores inseridos pelo contratante no workspace, a RIGOR atua em regra como operadora, seguindo as instruções do cliente controlador.</p></section>
    <section><h2>2. Dados tratados</h2><ul><li>Cadastro e conta: nome, e-mail, telefone, empresa, função e credenciais protegidas.</li><li>Faturamento: plano, status, identificadores da assinatura e dados necessários ao processador de pagamentos. A RIGOR não armazena o número completo do cartão.</li><li>Operação: obras, equipes, documentos, imagens, registros de campo e demais informações enviadas pelos usuários.</li><li>Segurança: endereço IP, dispositivo, registros de acesso, auditoria e eventos de erro.</li></ul></section>
    <section><h2>3. Finalidades e bases legais</h2><p>Tratamos dados para executar o contrato, autenticar usuários, prestar suporte, faturar, prevenir fraude, cumprir obrigações legais e exercer direitos. Comunicações opcionais e tecnologias não essenciais dependem de consentimento quando exigido.</p></section>
    <section><h2>4. Compartilhamento e transferências</h2><p>Dados podem ser processados por fornecedores de infraestrutura, banco de dados, armazenamento, autenticação, monitoramento e pagamentos, estritamente para prestar o serviço. Alguns provedores podem processar dados fora do Brasil com salvaguardas contratuais e técnicas aplicáveis.</p></section>
    <section><h2>5. Retenção e segurança</h2><p>Mantemos dados pelo período necessário ao contrato, à defesa de direitos e às obrigações legais. Aplicamos isolamento por empresa, controle de acesso, criptografia em trânsito, registros de auditoria e práticas de mínimo privilégio. Nenhum sistema é absolutamente invulnerável; incidentes relevantes serão tratados e comunicados conforme a legislação.</p></section>
    <section><h2>6. Direitos dos titulares</h2><p>O titular pode solicitar confirmação, acesso, correção, portabilidade quando aplicável, informação sobre compartilhamento, anonimização, bloqueio ou eliminação, oposição e revisão de decisões automatizadas, além de revogar consentimento. Solicitações serão verificadas para proteger a identidade e os dados envolvidos.</p></section>
    <section><h2>7. Canal de privacidade</h2><p>Envie solicitações para privacidade@rigorobras.com.br, informando nome, organização e pedido. Também é possível peticionar perante a Autoridade Nacional de Proteção de Dados.</p></section>
  </LegalPage>;
}
