import type React from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { alerts, kpis, modules, obras, people } from "@/lib/demo-data";
import { AlertTriangle, Calendar, CheckCircle2, DollarSign, Download, Eye, Filter, FileText, HardHat, Package, Plus, Search, ShieldCheck } from "lucide-react";

const toneMap: Record<string, string> = {
  orange: "bg-orange-50 text-awc-orange border-orange-100",
  success: "bg-green-100 text-green-800 border-green-100",
  warning: "bg-white text-amber-700 ring-1 ring-amber-200 border-amber-100",
  danger: "bg-red-50 text-awc-danger border-red-100",
  info: "bg-blue-50 text-awc-info border-blue-100",
};

export function PageChrome({ children }: { children: React.ReactNode }) {
  return <div className="mx-auto w-full max-w-[1540px] space-y-5 pb-8">{children}</div>;
}

export function PageHeader({ title, subtitle, action, actionHref, tabs = [], eyebrow = "Obras > Galpão Logístico Suzano" }: { title: string; subtitle?: string; action?: string; actionHref?: string; tabs?: string[]; eyebrow?: string }) {
  return (
    <div className="space-y-3">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <div className="mb-2 text-xs font-medium text-slate-500">{eyebrow} <span className="text-awc-orange">›</span> {title}</div>
          <h1 className="awc-title text-3xl leading-none">{title}</h1>
          {subtitle && <p className="mt-1 text-sm text-slate-500">{subtitle}</p>}
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm"><Filter className="mr-2 h-4 w-4" />Filtros</Button>
          <Button variant="outline" size="sm"><Download className="mr-2 h-4 w-4" />Exportar</Button>
          {action && (actionHref ? <Link href={actionHref} className="inline-flex h-9 items-center rounded-md bg-gradient-to-br from-[#ff4d00] to-[#ff7a1a] px-4 text-sm font-semibold text-white shadow-[0_10px_22px_rgba(255,77,0,.22)] transition hover:brightness-95"><Plus className="mr-2 h-4 w-4" />{action}</Link> : <Button size="sm" className="awc-btn-primary"><Plus className="mr-2 h-4 w-4" />{action}</Button>)}
        </div>
      </div>
      {tabs.length > 0 && <div className="flex gap-3 overflow-x-auto border-b border-slate-200">{tabs.map((tab, i) => <button key={tab} className={cn("awc-tab whitespace-nowrap", i === 0 && "awc-tab-active")}>{tab}</button>)}</div>}
    </div>
  );
}

export function StatCard({ label, value, hint, icon: Icon, tone = "orange" }: { label: string; value: string; hint: string; icon: React.ElementType; tone?: string }) {
  return <div className="awc-card p-4"><div className="flex items-center gap-4"><div className={cn("flex h-14 w-14 items-center justify-center rounded-full border", toneMap[tone])}><Icon className="h-7 w-7" /></div><div><p className="awc-title text-sm">{label}</p><p className={cn("text-3xl font-bold leading-tight", toneMap[tone]?.split(' ')[1])}>{value}</p><p className="text-xs text-slate-500">{hint}</p></div></div></div>;
}

export function ExecutiveDashboard() {
  return <PageChrome><PageHeader title="Dashboard Executivo" subtitle="Visão geral de todas as obras — Junho 2026" action="Nova obra" actionHref="/obras/novo" eyebrow="ObrasAWC" />
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{kpis.map(k => <StatCard key={k.label} {...k} />)}</div>
    <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
      <div className="awc-card p-5"><SectionTitle title="Obras em andamento" /><ObrasTable compact /></div>
      <div className="awc-card p-5"><SectionTitle title="Curva S — Geral" /><CurveChart /></div>
    </div>
    <div className="grid gap-4 xl:grid-cols-[1fr_.7fr]"><AlertsPanel /><CostPanel /></div>
  </PageChrome>;
}

export function ObrasScreen() {
  return <PageChrome><PageHeader title="Obras" subtitle="Carteira completa com progresso, prazo e risco" action="Nova obra" actionHref="/obras/novo" eyebrow="ObrasAWC" />
    <div className="awc-card p-4"><div className="mb-4 flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input className="awc-input w-full pl-9" placeholder="Buscar obra, cliente ou engenheiro..." /></div>{["Status", "Tipo", "Responsável", "Período"].map(f => <select key={f} className="awc-input"><option>{f}</option></select>)}</div><ObrasTable /></div>
  </PageChrome>;
}

export function ModuleScreen({ name }: { name: string }) {
  const mod = modules[name] || modules.relatorios; const Icon = mod.icon;
  const actionHref: Record<string, string> = { rdo: "/rdo/novo", obras: "/obras/novo", cronograma: "/cronograma", andamento: "/andamento", financeiro: "/financeiro", materiais: "/materiais", equipe: "/equipe", documentos: "/documentos", qualidade: "/qualidade", seguranca: "/seguranca", galeria: "/galeria", relatorios: "/relatorios" };
  return <PageChrome><PageHeader title={mod.title} subtitle={mod.subtitle} action={mod.action} actionHref={actionHref[name]} tabs={mod.tabs} />
    {name === "seguranca" ? <SafetyContent /> : name === "financeiro" ? <FinanceContent /> : name === "materiais" ? <MaterialsContent /> : name === "equipe" ? <TeamContent /> : name === "documentos" ? <DocsContent /> : name === "qualidade" ? <QualityContent /> : name === "galeria" ? <GalleryContent /> : name === "cronograma" ? <ScheduleContent /> : name === "andamento" ? <ProgressContent /> : <GenericContent icon={Icon} name={name} />}
  </PageChrome>;
}

function SectionTitle({ title, action }: { title: string; action?: string }) { return <div className="mb-4 flex items-center justify-between"><h2 className="awc-title text-xl">{title}</h2>{action && <button className="text-sm font-semibold text-awc-orange">{action}</button>}</div>; }
function Pill({ children, tone="success" }: { children: React.ReactNode; tone?: string }) { return <span className={cn("inline-flex rounded-md px-2 py-1 text-xs font-bold", tone === "danger" ? "bg-red-50 text-awc-danger" : tone === "warning" ? "bg-white text-amber-700 ring-1 ring-amber-200" : tone === "orange" ? "bg-orange-50 text-awc-orange" : "bg-green-100 text-green-800")}>{children}</span>; }
function Progress({ value, tone="orange" }: { value: number; tone?: string }) { return <div className="h-2 w-full rounded-full bg-slate-100"><div className={cn("h-2 rounded-full", tone === "danger" ? "bg-awc-danger" : tone === "success" ? "bg-awc-success" : "bg-awc-orange")} style={{width: `${value}%`}} /></div>; }

export function ObrasTable({ compact=false }: { compact?: boolean }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-3 py-3">Obra</th><th className="px-3 py-3">Cliente</th><th className="px-3 py-3">Responsável</th><th className="px-3 py-3">Prazo</th><th className="px-3 py-3">Avanço</th><th className="px-3 py-3">Status</th>{!compact && <th className="px-3 py-3 text-right">Ações</th>}</tr></thead><tbody>{obras.map((o) => <tr key={o.codigo} className="border-b last:border-0 hover:bg-slate-50"><td className="px-3 py-3"><Link href="/obras" className="font-semibold text-slate-900 hover:text-awc-orange">{o.nome}</Link><p className="text-xs text-slate-500">{o.codigo} · {o.cidade}</p></td><td className="px-3 py-3 text-slate-600">{o.cliente}</td><td className="px-3 py-3 text-slate-600">{o.engenheiro}</td><td className="px-3 py-3 text-slate-600">{o.prazo}</td><td className="px-3 py-3"><div className="flex min-w-[130px] items-center gap-2"><Progress value={o.realizado} tone={o.risco === "Crítico" ? "danger" : "orange"}/><span className="w-9 text-xs font-bold">{o.realizado}%</span></div></td><td className="px-3 py-3"><Pill tone={o.risco === "Crítico" ? "danger" : o.risco === "Atenção" ? "warning" : "success"}>{o.status}</Pill></td>{!compact && <td className="px-3 py-3 text-right"><Button variant="outline" size="sm"><Eye className="h-4 w-4" /></Button></td>}</tr>)}</tbody></table></div>; }

function CurveChart() { return <div className="h-64 rounded-xl bg-gradient-to-b from-slate-50 to-white p-4"><svg viewBox="0 0 520 220" className="h-full w-full"><path d="M20 180 C120 160,170 145,250 120 S390 70,500 48" fill="none" stroke="#98a2b3" strokeWidth="3" strokeDasharray="5 6"/><path d="M20 190 C110 178,170 155,250 135 S380 96,500 72" fill="none" stroke="#ff4d00" strokeWidth="5"/><g fill="#ff4d00">{[20,140,260,380,500].map((x,i)=><circle key={x} cx={x} cy={[190,166,132,98,72][i]} r="5" />)}</g></svg></div>; }
function AlertsPanel() { return <div className="awc-card p-5"><SectionTitle title="Alertas ativos" /><div className="space-y-3">{alerts.map((a,i)=><div key={a[0]} className="flex items-center gap-3 rounded-xl border p-3"><div className={cn("flex h-9 w-9 items-center justify-center rounded-full", i===3 ? "bg-white text-green-700 ring-1 ring-green-200" : i===2 ? "bg-white text-blue-700 ring-1 ring-blue-200" : "bg-white text-amber-700 ring-1 ring-amber-200")}><AlertTriangle className="h-4 w-4" /></div><div className="flex-1"><p className="font-semibold">{a[0]}</p><p className="text-xs text-slate-500">{a[1]}</p></div><Pill tone={a[2]==="Alta"?"danger":a[2]==="Média"?"warning":"success"}>{a[2]}</Pill></div>)}</div></div>; }
function CostPanel() { return <div className="awc-card p-5"><SectionTitle title="Custo total das obras" /><div className="flex items-center justify-center py-3"><div className="flex h-44 w-44 items-center justify-center rounded-full border-[18px] border-awc-success border-r-awc-orange border-b-slate-200"><div className="text-center"><p className="awc-title text-3xl">R$ 4,7M</p><p className="text-xs text-slate-500">Total</p></div></div></div><div className="grid grid-cols-3 gap-2 text-center text-xs"><span className="text-awc-success">Pago</span><span className="text-awc-orange">Comprometido</span><span className="text-slate-500">Em aberto</span></div></div>; }

function SafetyContent() { const cards: [string, string, string, React.ElementType, string][] = [['Dias sem acidente','47 dias','Desde 22/04/2026',Calendar,'success'],['DDS realizados','6/8','2 em falta',ShieldCheck,'orange'],['Treinamentos vencidos','2','Requer atenção',AlertTriangle,'danger'],['EPIs vencidos','1','Requer atenção',HardHat,'warning'],['Incidentes no mês','0','Nenhum incidente',CheckCircle2,'success']]; return <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{cards.map(([l,v,h,I,t]: [string, string, string, React.ElementType, string])=><StatCard key={l} label={l} value={v} hint={h} icon={I} tone={t}/>)}</div><div className="grid gap-4 xl:grid-cols-[1fr_.9fr]"><div className="awc-card p-5"><SectionTitle title="DDS — Diálogos de segurança" />{['Trabalho em altura — NR-35','Uso correto de EPIs','Movimentação de cargas — NR-11','DDS não realizado'].map((x,i)=><div key={x} className="flex items-center gap-4 border-b py-4 last:border-0"><CheckCircle2 className={cn("h-7 w-7",i===3?'text-slate-400':'text-awc-success')} /><div className="flex-1"><p className="font-semibold">{x}</p><p className="text-xs text-slate-500">07/06/2026 · {18+i} participantes · Tec. Seg. Paulo M.</p></div><Button variant="outline" size="sm">{i===3?'Registrar':'Ver detalhes'}</Button></div>)}<Button className="awc-btn-primary mt-3 w-full"><Plus className="mr-2 h-4 w-4"/>Registrar DDS</Button></div><AlertsPanel /></div><div className="awc-card p-5"><SectionTitle title="Registro de incidentes e acidentes — histórico" /><div className="mb-4 rounded-xl border border-green-200 bg-white p-4 text-sm font-semibold text-green-800">Sem acidentes com afastamento em 2026</div><ObrasTable compact /></div></>; }
function FinanceContent(){return <><div className="grid gap-4 md:grid-cols-4"><StatCard label="Valor contratado" value="R$ 2.100.000" hint="100% do contrato" icon={DollarSign} tone="info"/><StatCard label="Total gasto" value="R$ 582.240" hint="28% do contrato" icon={DollarSign} tone="orange"/><StatCard label="Comprometido" value="R$ 320.000" hint="15% em pedidos" icon={AlertTriangle} tone="warning"/><StatCard label="Margem prevista" value="18,4%" hint="R$ 386.400 projetado" icon={CheckCircle2} tone="success"/></div><div className="grid gap-4 xl:grid-cols-[1fr_.7fr]"><div className="awc-card p-5"><SectionTitle title="Comparativo orçado x realizado por etapa"/><ObrasTable compact /></div><CostPanel/></div></>}
function MaterialsContent(){return <><div className="grid gap-4 md:grid-cols-4"><StatCard label="Itens em estoque" value="47" hint="Materiais disponíveis" icon={Package} tone="info"/><StatCard label="Alertas de estoque" value="3" hint="Requer atenção" icon={AlertTriangle} tone="danger"/><StatCard label="Requisições pendentes" value="2" hint="Aguardando aprovação" icon={FileText} tone="orange"/><StatCard label="Entregas hoje" value="4" hint="Programadas" icon={Calendar} tone="success"/></div><div className="grid gap-4 xl:grid-cols-[1fr_320px]"><div className="awc-card p-5"><SectionTitle title="Estoque de materiais"/><ObrasTable compact /></div><AlertsPanel/></div></>}
function TeamContent(){return <div className="grid gap-4 xl:grid-cols-[1fr_360px]"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{people.map((p,i)=><div key={p} className="awc-card p-4"><div className="flex items-center gap-3"><div className="h-12 w-12 rounded-full bg-gradient-to-br from-orange-100 to-slate-200"/><div><p className="font-bold">{p}</p><p className="text-xs text-slate-500">{['Soldador','Armador','Pedreiro','Carpinteiro'][i%4]}</p></div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Pill>ASO ok</Pill><Pill tone={i%3?'success':'warning'}>EPI</Pill><Pill>Presente</Pill></div></div>)}</div><div className="awc-card p-5"><SectionTitle title="Detalhes do trabalhador"/><p className="font-bold">João Santos</p><p className="text-sm text-slate-500">Encarregado · Galpão Suzano</p><div className="mt-4 space-y-3 text-sm"><p>Documentos: <b className="text-awc-success">completos</b></p><p>Treinamentos: <b>NR-35, NR-18</b></p><p>EPIs: <b className="text-awc-warning">1 vencendo</b></p></div></div></div>}
function DocsContent(){return <div className="grid gap-4 xl:grid-cols-[280px_1fr]"><div className="awc-card p-4"><SectionTitle title="Categorias" />{['Projetos e Plantas','ARTs e RRTs','Ensaios e Laudos','Notas Fiscais','Contratos','Fotos de etapas'].map((x,i)=><div key={x} className={cn('flex justify-between rounded-lg px-3 py-3 text-sm transition',i===2?'bg-awc-orange text-white shadow-sm':'hover:bg-slate-50')}><span>{x}</span><b>{i+2}</b></div>)}</div><div className="awc-card p-5"><SectionTitle title="Ensaios e Laudos" action="Mais recentes"/><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-4">{Array.from({length:8}).map((_,i)=><div key={i} className="rounded-xl border p-4 text-center"><FileText className="mx-auto h-10 w-10 text-awc-orange"/><p className="mt-3 font-semibold">Laudo concreto {i+1}</p><p className="text-xs text-slate-500">Atualizado em 07/06/2026</p><Pill tone={i%3?'success':'warning'}>{i%3?'Aprovado':'Pendente'}</Pill></div>)}</div></div></div>}
function QualityContent(){return <><div className="grid gap-4 md:grid-cols-4"><StatCard label="Inspeções realizadas" value="23" hint="Este mês" icon={ShieldCheck} tone="info"/><StatCard label="Não conformidades" value="4" hint="Abertas" icon={AlertTriangle} tone="danger"/><StatCard label="NC críticas" value="1" hint="Alta prioridade" icon={AlertTriangle} tone="warning"/><StatCard label="Índice qualidade" value="91%" hint="Meta 95%" icon={CheckCircle2} tone="success"/></div><div className="awc-card p-5"><SectionTitle title="Não conformidades abertas"/><ObrasTable compact /></div></>}
function GalleryContent(){return <><div className="awc-card p-4"><div className="mb-4 grid gap-3 md:grid-cols-4"><input className="awc-input" placeholder="Buscar por etapa"/><select className="awc-input"><option>Todos os tipos</option></select><select className="awc-input"><option>Visualização grade</option></select><Button className="awc-btn-primary">Upload de fotos</Button></div><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-5">{Array.from({length:15}).map((_,i)=><div key={i} className="group aspect-[4/3] overflow-hidden rounded-xl bg-gradient-to-br from-slate-300 via-slate-200 to-orange-100 p-3 shadow-sm"><span className="rounded bg-awc-orange px-2 py-1 text-xs font-bold text-white">Montagem {i+1}</span></div>)}</div></div></>}
function ScheduleContent(){return <div className="awc-card p-5"><SectionTitle title="Cronograma — Galpão Logístico Suzano"/><div className="space-y-4">{['Fundações e terraplanagem','Montagem de pilares','Montagem de vigas','Laje pré-moldada','Fechamento e cobertura','Acabamento e entrega'].map((x,i)=><div key={x} className="grid grid-cols-[220px_1fr] items-center gap-4"><p className="font-semibold">{i+1}. {x}</p><div className="h-8 rounded bg-slate-100"><div className={cn('h-8 rounded',i<2?'bg-awc-success':i===2?'bg-awc-orange':'bg-slate-300')} style={{width:`${80-i*8}%`, marginLeft:`${i*5}%`}} /></div></div>)}</div></div>}
function ProgressContent(){return <><div className="grid gap-4 xl:grid-cols-3">{['Não iniciado','Em andamento','Concluído'].map((col,idx)=><div key={col} className="awc-card p-4"><SectionTitle title={col}/>{['Fundações','Montagem de pilares','Lajes e cobertura'].map((x,i)=><div key={x} className="mb-3 rounded-xl border p-3"><p className="font-semibold">{x}</p><p className="text-xs text-slate-500">Responsável: Equipe {i+1}</p><Progress value={idx===2?100:idx===1?45+i*15:5} tone={idx===2?'success':'orange'}/></div>)}</div>)}</div><div className="awc-card p-5"><SectionTitle title="Curva S — previsto x realizado"/><CurveChart/></div></>}
function GenericContent({icon: Icon}: { icon: React.ElementType; name?: string }){return <><div className="grid gap-4 md:grid-cols-4"><StatCard label="Itens ativos" value="24" hint="Atualizado agora" icon={Icon} tone="info"/><StatCard label="Pendentes" value="6" hint="Requer ação" icon={AlertTriangle} tone="warning"/><StatCard label="Concluídos" value="18" hint="No período" icon={CheckCircle2} tone="success"/><StatCard label="Críticos" value="2" hint="Alta prioridade" icon={AlertTriangle} tone="danger"/></div><div className="grid gap-4 xl:grid-cols-[1fr_.7fr]"><div className="awc-card p-5"><SectionTitle title="Lista operacional"/><ObrasTable compact /></div><AlertsPanel/></div></>}
