import { LegalPage } from '@/components/legal/legal-page';
export const metadata = { title: 'Termos de Uso | RIGOR' };
export default function TermsPage() {
  return <LegalPage title="Termos de Uso" description="Regras para contratação e uso da plataforma RIGOR de gestão de obras.">
    <section><h2>1. Objeto e aceitação</h2><p>Estes Termos regem o acesso à plataforma RIGOR, oferecida pela empresa responsável pela marca RIGOR OBRAS (“RIGOR”). Ao criar uma conta, contratar um plano ou utilizar o serviço, o cliente declara ter poderes para representar sua organização e aceita estes Termos e a Política de Privacidade.</p></section>
    <section><h2>2. Conta e responsabilidades</h2><ul><li>O cliente deve fornecer dados verdadeiros, manter credenciais em sigilo e informar imediatamente acessos indevidos.</li><li>Administradores controlam usuários, permissões e conteúdo do seu workspace.</li><li>É proibido usar o serviço para fins ilícitos, violar direitos de terceiros, introduzir código malicioso ou tentar acessar dados de outro cliente.</li></ul></section>
    <section><h2>3. Planos, cobrança e cancelamento</h2><p>Os valores, limites e periodicidade escolhidos são exibidos antes da contratação. A cobrança recorrente é processada pela AbacatePay no cartão cadastrado. Trocas de plano passam a valer no próximo ciclo informado no checkout. O cancelamento solicitado no painel é imediato e interrompe o acesso aos recursos pagos, conforme a política operacional do processador.</p></section>
    <section><h2>4. Conteúdo e propriedade intelectual</h2><p>O cliente mantém a titularidade dos dados, documentos e imagens enviados. Concede à RIGOR autorização limitada para armazenar, processar e disponibilizar esse conteúdo exclusivamente para prestar e proteger o serviço. A plataforma, marca, interfaces e código pertencem à RIGOR ou a seus licenciadores.</p></section>
    <section><h2>5. Disponibilidade e suporte</h2><p>A RIGOR emprega esforços razoáveis de continuidade, segurança, backup e manutenção, mas pode realizar intervenções programadas ou emergenciais. Canais e níveis de suporte variam conforme o plano contratado.</p></section>
    <section><h2>6. Inadimplência e encerramento</h2><p>Falhas de pagamento podem gerar novas tentativas, restrição de funcionalidades e cancelamento. O cliente poderá solicitar exportação dos dados disponíveis antes do encerramento, observados prazos técnicos, obrigações legais e políticas de retenção.</p></section>
    <section><h2>7. Limitação e legislação</h2><p>Na extensão permitida pela lei, a RIGOR não responde por decisões de engenharia tomadas sem validação profissional, indisponibilidades de terceiros ou dados inseridos incorretamente pelo cliente. Aplicam-se as leis brasileiras, inclusive o Código de Defesa do Consumidor quando cabível.</p></section>
    <section><h2>8. Contato</h2><p>Dúvidas comerciais: comercial@rigorobras.com.br. Privacidade e dados pessoais: privacidade@rigorobras.com.br.</p></section>
  </LegalPage>;
}
